# Generated by Django 3.1 on 2020-08-18 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200818_0022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='CowSpeech',
        ),
    ]
