# Generated by Django 3.1 on 2020-08-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200818_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowspeech',
            name='user_text',
            field=models.TextField(default='Enter text here!', max_length=100),
        ),
    ]
