# Generated by Django 3.1 on 2020-08-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200818_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowspeech',
            name='user_text',
            field=models.TextField(default='Enter text', max_length=100),
        ),
    ]
